"use client"
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useChainId } from 'wagmi';
import { useState } from 'react';
import { TxRelayPriceResponse } from '../utils/types';
import PriceView from '../components/PriceView';
import classNames from 'classnames';

const Home: NextPage = () => {

  const { address } = useAccount();
  const chainId = useChainId();

  //const chainId = chain?.id || 137;

  const [finalize, setFinalize] = useState(false);
  const [checkAppoval, setCheckApproval] = useState(false);
  const [price, setPrice] = useState<TxRelayPriceResponse | undefined>();
  const [quote, setQuote] = useState();
  const [tradeHash, setTradeHash] = useState<string | undefined>();

  return (
    <div className={classNames(styles.container, '')}>
      <Head>
        <title>0x gasless swap applet</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={classNames(styles.main, '')}>
        <PriceView
          chainId={chainId}
          taker={address}
          setPrice={setPrice}
          setFinalize={setFinalize}
          price={price}
        />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Wakeup
        </a>
      </footer>
    </div>
  );
};

export default Home;
