"use client";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount, useChainId } from "wagmi";
import { useState } from "react";
import classNames from "classnames";
import { TxRelayPriceResponse } from "../shared/types";
import { Toaster } from "sonner";
import PriceView from "../frontend/components/PriceView";

const Home: NextPage = () => {
    const [finalize, setFinalize] = useState(false);
    const [checkAppoval, setCheckApproval] = useState(false);
    const [price, setPrice] = useState<TxRelayPriceResponse | undefined>();
    const [quote, setQuote] = useState();
    const [tradeHash, setTradeHash] = useState<string | undefined>();

    return (
        <div className={styles.container}>
            <Head>
                <title>0x gasless swap applet</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Toaster />
            <main className={styles.main}>
                <PriceView />
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://rainbow.me"
                    rel="noopener noreferrer"
                    target="_blank"
                >
                    Wakeup
                </a>
            </footer>
        </div>
    );
};

export default Home;
